# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'g:\biye\qt\01.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(897, 677)
        self.closeWinBtb = QtWidgets.QPushButton(Form)
        self.closeWinBtb.setGeometry(QtCore.QRect(270, 150, 93, 28))
        self.closeWinBtb.setObjectName("closeWinBtb")

        self.retranslateUi(Form)
        self.closeWinBtb.clicked.connect(Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.closeWinBtb.setText(_translate("Form", "关闭窗口"))
